version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env
